### ISSUE TITLE
Is it still repo for https://www.inkline.io?

### ISSUE THREAD

**Issue by Eternal-Rise** [inkline/inkline.io#7]
I want to check smth, but have some issues to run this project locally. So I came here to write an issue, but  I see major differences between inkline.io and content in this repo.

**Comment by alexgrozav** [comment]
The `main` branch is used for the active development of Inkline 4 docs and is deployed on https://next.inkline.io. You'll want to look at the `inkline@3` branch for the https://inkline.io website.

**Comment by Eternal-Rise** [comment]
Now I see, thanx
